import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
        <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>
      <Head>
        <title>Shopify-Design-v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}